### ISSUE TITLE
Implement data fetching from W3C

### ISSUE THREAD

**Issue by ronaldtse** [ietf-tools/relaton-data-w3c#1]
Use relaton-w3c. Depends on

* https://github.com/relaton/relaton-w3c/issues/11
* https://github.com/relaton/relaton-w3c/issues/12

**Comment by andrew2net** [comment]
@ronaldtse I've implemented relaton/relaton-data-w3c when did the task https://github.com/relaton/relaton-w3c/issues/12. Do we need to implement the same here?

**Comment by ronaldtse** [comment]
Yes please, thanks. I think @strogonoff prefers to have Relaton data to read for indexing.

**Comment by strogonoff** [comment]
Hold on…

BibXML project indexer [uses the following logic](https://github.com/ietf-ribose/bibxml-indexer#dataset-sources) (note org names):

* ``bibxml-data-{dataset_id}`` repositories under ``ietf-ribose`` Github user are treated as BibXML sources, and
* ``relaton-data-{dataset_id}`` repositories under ``relaton`` Github user are treated as Relaton sources
  (until ``relaton-bib-py`` library takes care of conversion).

This currently works: http://34.229.41.119:8000/w3c/

My concern is:

- If we have `ietf-ribose/relaton-data-w3c`, it will not be used by default.
- We can override Relaton dataset source in the indexer for W3C, but what would be the point if we can use `relaton/relaton-data-w3c` until we incorporate `relaton-bib-py`?

Cc @ronaldtse

**Comment by ronaldtse** [comment]
> relaton-data-{dataset_id} repositories under relaton Github user are treated as Relaton sources

@strogonoff For the delivery to IETF, *all data source repos* will be under the `https://github.com/ietf-ribose` account. i.e. we will not use any repos from the GH org `https://github.com/relaton`.

**Comment by andrew2net** [comment]
@ronaldtse In which format should be documents in this repo? RelatonXML, BibXML, YAML?

**Comment by strogonoff** [comment]
@andrew2net  The service expects:

- `/ietf-ribose/bibxml-data-` in BibXML
- `/ietf-ribose/relaton-data-` in Relaton YAML

**Comment by ronaldtse** [comment]
(Thank you @strogonoff )

**Comment by ronaldtse** [comment]
Done in 46989eeae6c04c3b8c3483243a4f59a8f5134896.
