### ISSUE TITLE
`docid` is still not a list

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-w3c#2]
Example: https://github.com/ietf-ribose/relaton-data-w3c/blob/main/data/WD-WAI-ARIA-PRACTICES-1.2-20191218.yaml#L10

**Comment by andrew2net** [comment]
@strogonoff this file doesn't exist in the data source anymore, so it isn't updated.
@ronaldtse should we remove files that were removed in the source dataset?

**Comment by ronaldtse** [comment]
@andrew2net yes -- we should definitely remove files that were removed in the source dataset. It should just be a Git change (i.e. delete all files then generate).

**Comment by andrew2net** [comment]
@strogonoff I've updated GitHub action but I don't have permission to push to the main branch. Please merge the PR https://github.com/ietf-ribose/relaton-data-w3c/pull/3

**Comment by ronaldtse** [comment]
@andrew2net you have access now.

**Comment by ronaldtse** [comment]
Closing since #3 is merged.
