### ISSUE TITLE
Malformed `formattedref`

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-w3c#4]
This is what we have:

https://github.com/ietf-ribose/relaton-data-w3c/blob/ca88f2c20036c25f3f1232922d1f9eeb949fbc67/data/OBSL-WIDGETS-DIGSIG-20181011.yaml#L73-L76

This is what is expected:

https://github.com/ietf-ribose/relaton-data-ieee/blob/900d7b048dd9b5a72fdf8fa98646c97186d1e007/data/IEEE_P1361_D-5.2014-02.yaml#L62-L74

**Comment by strogonoff** [comment]
I don’t know if what we have is allowed by the grammar:

https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc#L69-L73

Anyone can help interpreting that part? Plain string should be expected or not?

**Comment by ronaldtse** [comment]
@strogonoff I think you're right here. @andrew2net can you help check and create the corresponding task? Thanks.

**Comment by andrew2net** [comment]
> This is what we have:
> 
> https://github.com/ietf-ribose/relaton-data-w3c/blob/ca88f2c20036c25f3f1232922d1f9eeb949fbc67/data/OBSL-WIDGETS-DIGSIG-20181011.yaml#L73-L76
> 
> This is what is expected:
> 
> https://github.com/ietf-ribose/relaton-data-ieee/blob/900d7b048dd9b5a72fdf8fa98646c97186d1e007/data/IEEE_P1361_D-5.2014-02.yaml#L62-L74

@strogonoff sorry, I don't understand the issue. These are 2 different documents. What is the problem with the formattedrefs?



> I don’t know if what we have is allowed by the grammar:
> 
> https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc#L69-L73
> 
> Anyone can help interpreting that part? Plain string should be expected or not?

The grammar doesn't describe the structure of the references. We use only plain string as formattedref.

**Comment by strogonoff** [comment]
@andrew2net  documents use different data structure for formattedref

**Comment by andrew2net** [comment]
@strogonoff yes, they have different structures because they are issued by different publishers. We use so-called PubIDs to reference documents. Each publisher has its own PubID structure but not all publishers have a PubID specification.
Some information about PubID can be found here https://github.com/metanorma/metanorma-nist/issues/168

**Comment by strogonoff** [comment]
@andrew2net 

This does not have to do with publishers, but with adherence to Relaton spec.

- Relaton spec says that formatted ref is a formatted string instance.
- Formatted string instance must have `content` and `format` properties.
- Parser that expects a formatted string fails on a plain string.

Unless Relaton spec is fuzzy and allows formatted ref to also be a plain string, this:

```
relation:
- type: obsoletes
  bibitem:
    formattedref: W3C REC-widgets-digsig-20130418
```

Should be changed to this:

```
relation:
- type: obsoletes
  bibitem:
    formattedref:
      content: W3C REC-widgets-digsig-20130418
      format: text/plain
```

**Comment by andrew2net** [comment]
> This does not have to do with publishers, but with adherence to Relaton spec.

Sorry, it's my mistake. I supposed we discussed content of formatedref.

> * Relaton spec says that formatted ref is a formatted string instance.

Do you mean this [spec](https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc#L69-L73)? It describes the Relaton model representation in RleatonXML format. YAML format is described here https://github.com/relaton/relaton-bib/blob/main/docs/hash.adoc

> * Formatted string instance must have `content` and `format` properties.

The RNC spec says that formattedfer must have `content` but `format` is optional.
The YAML format spec has examples of formattedref what show if it doesn't content `format` or `language` it's represented as plain text.

> * Parser that expects a formatted string fails on a plain string.

Why can't parser check if a formattedref is a string or an object?

**Comment by andrew2net** [comment]
@strogonoff can we close this issue?

**Comment by strogonoff** [comment]
I think after the switch to `docid` it‘s OK, `formattedref` format doesn’t matter much.
