### ISSUE TITLE
`docid` on W3C documents is still not a list

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-w3c#5]
Example: https://github.com/ietf-ribose/relaton-data-w3c/blob/main/data/WD-SCREEN-WAKE-LOCK-20210930.yaml

This means structural lookups by docid, which rely on it being a list, [do not work](https://dev.bibxml.org/search/?query=%7B%22docid%22%3A+%5B%7B%22id%22%3A+%22W3C+WD-screen-wake-lock-20210930%22%7D%5D%7D&query_format=json_struct).

**Comment by ronaldtse** [comment]
Ping @andrew2net for help.

**Comment by andrew2net** [comment]
fixed
